language: python
dist: xenial
sudo: required

env:
  - ORACLE_HOME=/u01/app/oracle/product/12.1.0/xe ORACLE_SID=XE OCI_LIB_DIR=/u01/app/oracle/product/12.1.0/xe/lib LD_LIBRARY_PATH=/u01/app/oracle/product/12.1.0/xe/lib

before_install:
  - sudo apt-get install p7zip-full
  - wget https://raw.githubusercontent.com/acekun141/oracle18c/master/setup_and_install.sh
